# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.24.1
# 

Name:       libXdmcp

# >> macros
# << macros

Summary:    X.Org X11 libXdmcp runtime library
Version:    1.1.1
Release:    1
Group:      System/Libraries
License:    MIT
URL:        http://www.x.org/
Source0:    http://xorg.freedesktop.org/releases/individual/lib/%{name}-%{version}.tar.bz2
Source100:  libXdmcp.yaml
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(xproto)

%description
X Display Manager Control Protocol library


%package devel
Summary:    Development components for the libXdmcp library
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
X Display Manager Control Protocol library files.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post


%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
# >> files
%doc AUTHORS COPYING README ChangeLog
%{_libdir}/libXdmcp.so.6
%{_libdir}/libXdmcp.so.6.0.0
# << files

%files devel
%defattr(-,root,root,-)
# >> files devel
%dir %{_includedir}/X11/
%{_includedir}/X11/Xdmcp.h
%{_libdir}/libXdmcp.so
%{_libdir}/pkgconfig/xdmcp.pc
%doc %{_docdir}/libXdmcp/xdmcp.xml
# << files devel
